version: "3"
services:
    db_server:
        image: kamatimaru/mysql57-ja:latest
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: demo